#!/usr/bin/env python3

import os

# Define modules files paths
oldModulesPath = os.path.join(os.path.dirname(__file__), '../.gitmodules')
newModulesPath = os.path.join(os.path.dirname(__file__), '../dist/.gitmodules')

# Read top level .gitmodules file and populate newModules string
newModules = None
with open(oldModulesPath) as oldModulesFile:
    oldModules = oldModulesFile.read()
    newModules = oldModules.replace('\tpath = dist/', '\tpath = ')

# Write to new file
with open(newModulesPath, 'w') as newModulesFile:
    newModulesFile.write(newModules)

# Continue with deployment script
deploy = os.path.join(os.path.dirname(__file__), 'lib/deploy')
os.system(deploy)

